config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'posts#index'

  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true, length: { maximum: 140 }
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings
end

app/models/tagging.rb
# frozen_string_literal: true

class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def top; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
  end

  def search
    # 検索フォーム
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
    render('posts/index')
  end

  def show; end

  def new
    @post = Post.new
    @post.taggings.build
  end

  def create
    @post = Post.new(title: params[:title],
                     url: params[:url],
                     reference: params[:reference])
    tag_input
    if @post.save
      redirect_to('/')
      flash[:notice] = '投稿が作成されました。'
    else
      render('posts/new')

    end
  end

  def edit; end

  def update
    @post.title = params[:title]
    @post.url = params[:url]
    @post.reference = params[:reference]
    tag_input
    if @post.save
      redirect_to root_path
      flash[:notice] = '投稿が編集されました。'
    else
      render('posts/edit')
    end
  end

  def destroy
    @post.destroy
    redirect_to('/')
    flash[:notice] = '投稿が削除されました。'
  end

  def post_params
    params.require(:post).permit(:title, :reference, :url, :tag, :tag_id, :post_id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end

  private

  def tag_input
    tgs = params[:tag].split(',')
    tgs. each do |t|
      @post.tags.build(name: t)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/home/top.html.erb
<div class="main posts-index">
<h1>yay</h1>
<p>this is toppage</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <header>
      <div class="header-logo">
        <%= link_to FujisanConfig.title, root_path %>
      </div>
      <ul class="header-menus">
        
        <li>
          <a href="/">コミュニティ一覧</a>
        </li>
        <li>
          <a href="/posts/new">新しいコミュニティ</a>
        </li>
      </ul>
    </header>
    <% if flash[:notice]%>
      <div class = "flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">編集する</h1>
    
    <%= form_tag(post_path, method: :patch) do %>

      <div class="form">
        <div class="form-body">
          
          <% @post.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>
          <p>タイトル</p>
          <textarea name = "title" ><%= @post.title %></textarea>
          <p>参加url</p>
          
          <textarea name = "url"><%= @post.url %></textarea>
          <p>説明</p>
          <textarea name = "reference"><%= @post.reference %></textarea>

          <p>タグ , で区切って入力）</p>
          <textarea name = "tag" ><%= @post.tags.pluck(:name).join(",") %></textarea>
          <input type="submit" value="投稿">
           
        
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
  
    <%= search_form_for(@q,url:posts_path) do |f| %>
      <%= f.label :title, "Keyword" %>
      <%= f.search_field :title_cont %>
      <%= f.submit "検索" %>
    <% end %>

    <!--投稿始まり-->
    <% @posts.each do |post| %>
      <div class="posts-index-item">
    
        <%= link_to(post.title,"/posts/#{post.id}") %><br>
        
        <%= link_to '<参加するボタン>', post.url %><br>
        
        <%= post.reference %><br>
        
        <% post.tags.each do |tag| %>
          <%= tag.name %> 
        <%end%>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">投稿する</h1>
    <div class="form">
      <div class="form-body">
        <%= form_tag(posts_path, method: :post) do %>
          <p>コミュニティのタイトル</p>
          <% @post.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>
          <textarea name = "title" ></textarea>
          <p>参加url</p>
          
          <textarea name = "url"></textarea>
          <p>説明</p>
          
          <textarea name = "reference"></textarea>
          <p>タグ , で区切って入力）</p>
          <textarea name = "tag" ></textarea>
          <input type="submit" value="投稿">
        <% end %>      
      </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container_show">
    <div class="posts-show-item">
      <p>
        <%= @post.title%>
      </p>
      <p>
        <%= link_to '<参加するボタン>', @post.url %>
      </p>
      <p>
        <%= @post.reference%>
      </p>
      <div class="post-time">
        <%= @post.created_at%>
      </div>
       <div class="post-menus">
        <%= link_to("編集", edit_post_path) %>
        <%= link_to '削除', post_path, method: :delete, data: {confirm: '本当に削除しますか？'} %>
      </div>
    </div>
    
  </div>
</div>